version: '3'

services:
  app:
    image: 'test:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=walethea
      - SPRING_DATASOURCE_PASSWORD=toor
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=walethea
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=test
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
volumes:
  db-data:
    external: true